# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('custom_id', models.CharField(max_length=100, unique=True)),
                ('image_url', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
