# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170405_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_day',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_day',
            new_name='start_date',
        ),
    ]
