# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('liked', models.BooleanField()),
                ('seconds_viewed', models.IntegerField(default=-1)),
                ('seen_date', models.DateField(auto_now_add=True)),
                ('seen_time', models.TimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='userevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userevents.UserEvent'),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together=set([('user_id', 'event', 'liked')]),
        ),
    ]
