# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='user_event',
            new_name='userevent',
        ),
    ]
