# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userevents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='create_time',
        ),
        migrations.AddField(
            model_name='userevent',
            name='seen_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 7, 9, 54, 42, 195114)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userevent',
            name='seen_time',
            field=models.TimeField(default=datetime.datetime(2017, 4, 7, 9, 55, 3, 680265)),
            preserve_default=False,
        ),
    ]
