# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userevents', '0002_auto_20170404_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='seen_at',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
