# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
